POST http://localhost:3000/api/robot/checkVccode
content-type: application/json
//这里必须有一空行

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNjc0NTQ3NzE1NjQxLCJsb2NrIjoidGVzdCIsInN0YXRlIjoi6aqM6K-B5LitIiwiaWF0IjoxNjc0NTQ3NzE1LCJleHAiOjE2NzQ1NDgwMTV9.PlDsC0aM6LHfaly9LBzT6Qv612lQoUtw4jIXEU4ieME",
    "vccode":"5Kfx"
}